name: Python application

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Make scripts executable
      run: chmod +x *.py
    - name: Lint with pylint
      run: |
        pylint **/*.py
    - name: Test with unittest
      run: |
        coverage run -m unittest discover
        coverage report
